
# Pipeline/pipeline.py 
import gc

import torch 
import torch.nn as nn
import torch.nn.init as init
from model.factory import get_model
from train.trainer import Trainer
from data.data_loader import DataLoader



class Pipeline:
    """
    Pipeline Architecture Outline:
    ------------------------------
    1. Dependency Injection: Initialize with 'args' and 'equation' instance.
    2. Lazy-Loaded Components:
        - model: (Instance of nn.Module)
        - data_loader: (Instance of Dataloader) the tool for get_data(data_loader)
        - data: (Generated by equation.get_data)
        - trainer: (Instance of Trainer)
    3. Polymorphism Structure:
        - Base Class: BaseEquation (Defines the interface)
        - Subclasses: e.g., Poisson, Burgers (Implement specific physics)
        - Subclass Overrides: Must implement 'get_data', 'compute_loss'
    """
    def __init__(self, args, equation,callbacks=None):
        self.args = args
        self.eq = equation  # BaseEquation Instance from Equation/_base.py
        
        self._model = None
        self._trainer = None
        self._data_loader = None
        self._data = None 
        self.callbacks=callbacks or []
        self.seed=args.seed
        torch.manual_seed(self.seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(self.seed)
        
        
    @property
    def model(self):
        """load model lazily"""
        if self._model is None:
            print("[Pipeline] build model...")
            #model(args)
            self._model =get_model(self.args).to(self.args.device)
        if getattr(self.args, "use_double", False):
            self._model = self._model.double()

        return self._model
    def reset_model(self):
        """clear cached model, rebuild on next access"""
        if self._model is not None:
            del self._model
            self._model = None
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    @property
    def trainer(self):
        if self._trainer is None:
            print("[Pipeline] Building trainer...")
            # Passing self.eq to trainer allows the trainer to access polymorphic loss functions
            self._trainer = Trainer(self.model, self.eq, self.args,callbacks=self.callbacks)
        return self._trainer
    
    def reset_trainer(self):
        """clear cached trainer, rebuild on next access"""
        if self._trainer is not None:
            del self._trainer
            self._trainer = None
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    @property
    def data_loader(self):
        """load data loader lazily"""
        if self._data_loader is None:
            print("[Pipeline] build data_loader...")
            self._data_loader = DataLoader(self.args)
        return self._data_loader

    @property
    def data(self):
        """load data lazily, equation decides how to generate data"""
        if self._data is None:
            print("[Pipeline] generate data...")
            self._data = self.eq.get_data(self.data_loader)
        return self._data